install.packages("shiny",dependencies=TRUE, repos='http://cran.rstudio.com/', Ncpus=1)
install.packages("shinyauthr",dependencies=TRUE, repos='http://cran.rstudio.com/')
shinytest::installDependencies()
install.packages("shinydashboard",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("tidyr",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("ggplot2",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("sf",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("lubridate",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("stringr",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("plotly",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("shinyBS",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("shinyjs",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("leaflet",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("shinyalert",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("magrittr",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("shinycssloaders",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("reactable",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("tippy",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("shinyWidgets",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("auth0",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("data.table",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("dplyr",dependencies=TRUE, repos='http://cran.rstudio.com/')

install.packages("sp",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("future",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("future.apply",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("foreach",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("doParallel",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("wrapr",dependencies=TRUE, repos='http://cran.rstudio.com/')

install.packages("devtools",dependencies=TRUE, repos='http://cran.rstudio.com/')
devtools::install_github('onaio/ona.R')
