name: dc_dashboard_pipeline

on:
  push:
    branches: 
    - "release/development" 
    - "release/staging"
    - "release/production"

permissions:
  contents: read

jobs:
  build_dev:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Download envs from S3 bucket
      run: |
        aws s3 cp s3://scio-project-envs/eia2030-dc-dashboard/_.Renviron .Renviron
        aws s3 cp s3://scio-project-envs/eia2030-dc-dashboard/_auth0-dev.yml _auth0.yml

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # - name: Build and Push Docker Image (dev)
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: .
    #     push: true
    #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/eia2030-dc-dashboard:dev

    - name: Set up SSH
      run: |
        echo "${{ secrets.DEPLOY_KEY }}" > private_key
        chmod 600 private_key
        eval $(ssh-agent -s)
        ssh-add private_key

    - name: Deploy via SSH  
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.SSH_USER }}@${{ secrets.DEV_DEPLOYMENT_INSTANCE }} -p ${{ secrets.SSH_PORT }} export ENV=dev
        ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.SSH_USER }}@${{ secrets.DEV_DEPLOYMENT_INSTANCE }} -p ${{ secrets.SSH_PORT }} docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
        ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.SSH_USER }}@${{ secrets.DEV_DEPLOYMENT_INSTANCE }} -p ${{ secrets.SSH_PORT }} sudo mkdir -p /var/lib/app/eia2030-dc-dashboard
        ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.SSH_USER }}@${{ secrets.DEV_DEPLOYMENT_INSTANCE }} -p ${{ secrets.SSH_PORT }} sudo chown -R ${SSH_USER}:${SSH_USER} /var/lib/app/eia2030-dc-dashboard
        ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.SSH_USER }}@${{ secrets.DEV_DEPLOYMENT_INSTANCE }} -p ${{ secrets.SSH_PORT }} mv docker-compose.yml /var/lib/app/eia2030-dc-dashboard
        ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.SSH_USER }}@${{ secrets.DEV_DEPLOYMENT_INSTANCE }} -p ${{ secrets.SSH_PORT }} docker-compose -f /var/lib/app/eia2030-dc-dashboard/docker-compose.yml down
        ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.SSH_USER }}@${{ secrets.DEV_DEPLOYMENT_INSTANCE }} -p ${{ secrets.SSH_PORT }} docker-compose -f /var/lib/app/eia2030-dc-dashboard/docker-compose.yml pull
        ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.SSH_USER }}@${{ secrets.DEV_DEPLOYMENT_INSTANCE }} -p ${{ secrets.SSH_PORT }} docker-compose -f /var/lib/app/eia2030-dc-dashboard/docker-compose.yml up -d
        ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.SSH_USER }}@${{ secrets.DEV_DEPLOYMENT_INSTANCE }} -p ${{ secrets.SSH_PORT }} docker image prune -a -f