name: dc_dashboard_pipeline

on:
  push:
    branches: 
    - "release/development" 
    - "release/staging"
    - "release/production"

permissions:
  contents: read

jobs:
  dev:
    name: Build & Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release/development'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Download envs from S3 bucket
      run: |
        aws s3 cp s3://scio-project-envs/eia2030-dc-dashboard/_.Renviron .Renviron
        aws s3 cp s3://scio-project-envs/eia2030-dc-dashboard/_auth0-dev.yml _auth0.yml

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Docker Image (dev)
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/eia2030-dc-dashboard:dev
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Transfer deploy script
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.DEV_DEPLOYMENT_INSTANCE }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: deploy.sh, docker-compose.yml
        target: "~"
    
    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEV_DEPLOYMENT_INSTANCE }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          export ENV=dev
          export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          export DOCKERHUB_PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}
          export REPO_NAME=eia2030-dc-dashboard
          export SSH_USER=${{ secrets.SSH_USER }}
          bash deploy.sh
          rm deploy.sh
          
  stg:
    name: Build & Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release/staging'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Download envs from S3 bucket
      run: |
        aws s3 cp s3://scio-project-envs/eia2030-dc-dashboard/_.Renviron .Renviron
        aws s3 cp s3://scio-project-envs/eia2030-dc-dashboard/_auth0-stg.yml _auth0.yml

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Docker Image (stg)
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/eia2030-dc-dashboard:stg
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Transfer deploy script
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.STG_DEPLOYMENT_INSTANCE }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: deploy.sh, docker-compose.yml
        target: "~"
    
    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.STG_DEPLOYMENT_INSTANCE }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          export ENV=stg
          export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          export DOCKERHUB_PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}
          export REPO_NAME=eia2030-dc-dashboard
          export SSH_USER=${{ secrets.SSH_USER }}
          bash deploy.sh
          rm deploy.sh

  prod:
    name: Build & Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release/production'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Download envs from S3 bucket
      run: |
        aws s3 cp s3://scio-project-envs/eia2030-dc-dashboard/_.Renviron .Renviron
        aws s3 cp s3://scio-project-envs/eia2030-dc-dashboard/_auth0-prod.yml _auth0.yml

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Docker Image (prod)
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/eia2030-dc-dashboard:prod
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Transfer deploy script
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.PROD_DEPLOYMENT_INSTANCE }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: deploy.sh, docker-compose.yml
        target: "~"
    
    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.PROD_DEPLOYMENT_INSTANCE }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          export ENV=prod
          export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          export DOCKERHUB_PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}
          export REPO_NAME=eia2030-dc-dashboard
          export SSH_USER=${{ secrets.SSH_USER }}
          bash deploy.sh
          rm deploy.sh