name: dc_dashboard_pipeline

on:
  push:
    branches: 
    - "release/development" 
    - "release/staging"
    - "release/production"

permissions:
  contents: read

jobs:
  build_dev:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Download envs from S3 bucket
      run: |
        aws s3 cp s3://scio-project-envs/eia2030-dc-dashboard/_.Renviron .Renviron
        aws s3 cp s3://scio-project-envs/eia2030-dc-dashboard/_auth0-dev.yml _auth0.yml

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # - name: Build and Push Docker Image (dev)
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: .
    #     push: true
    #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/eia2030-dc-dashboard:dev

    - name: Transfer deploy script
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.DEV_DEPLOYMENT_INSTANCE }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: deploy.sh
        target: "~"
    
    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEV_DEPLOYMENT_INSTANCE }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          bash deploy.sh
        envs: |          
          ENV=dev
          DOCKERHUB_USERNAME=${DOCKERHUB_USERNAME}
          DOCKERHUB_PASSWORD=${DOCKERHUB_PASSWORD}
          REPO_NAME=eia2030-dc-dashboard
          SSH_USER=${SSH_USER}